import type { Card } from './gameTypes';

const img = 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=512';

export const fallbackCards: Card[] = [
  { id:'et-1',name:'He-Man',cost:12,faction:'Eternia',rarity:'Lendária',type:'Criatura',attack:8,health:8,description:'Campeão de Grayskull.',image_url:img,effect_type:'buff_team',effect_value:2,duration:2,trigger_type:'on_play',reactive_slot:null },
  { id:'et-2',name:'Teela',cost:6,faction:'Eternia',rarity:'Épica',type:'Criatura',attack:4,health:5,description:'Guardiã tática.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'et-3',name:'Man-At-Arms',cost:5,faction:'Eternia',rarity:'Rara',type:'Criatura',attack:3,health:5,description:'Engenheiro de batalha.',image_url:img,effect_type:'shield',effect_value:2,duration:2,trigger_type:'on_play',reactive_slot:null },
  { id:'et-4',name:'Sorceress',cost:10,faction:'Eternia',rarity:'Lendária',type:'Criatura',attack:2,health:6,description:'Compra 2 cartas.',image_url:img,effect_type:'draw',effect_value:2,duration:null,trigger_type:'on_play',reactive_slot:null },
  { id:'et-5',name:'Battle Cat',cost:7,faction:'Eternia',rarity:'Épica',type:'Criatura',attack:5,health:4,description:'Fera leal.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'et-6',name:'Orko',cost:4,faction:'Eternia',rarity:'Rara',type:'Criatura',attack:2,health:3,description:'Compra 1 carta.',image_url:img,effect_type:'draw',effect_value:1,duration:null,trigger_type:'on_play',reactive_slot:null },
  { id:'et-7',name:'Ram Man',cost:3,faction:'Eternia',rarity:'Comum',type:'Criatura',attack:4,health:2,description:'Impacto bruto.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'et-8',name:'Stratos',cost:2,faction:'Eternia',rarity:'Comum',type:'Criatura',attack:2,health:2,description:'Ataque aéreo.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'et-9',name:'Man-E-Faces',cost:5,faction:'Eternia',rarity:'Rara',type:'Criatura',attack:3,health:4,description:'Versátil.',image_url:img,effect_type:'adapt',effect_value:1,duration:1,trigger_type:'on_turn_start',reactive_slot:null },
  { id:'et-10',name:'Buzz-Off',cost:3,faction:'Eternia',rarity:'Comum',type:'Criatura',attack:2,health:3,description:'Escaramuça.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'et-11',name:'Espada do Poder',cost:2,faction:'Eternia',rarity:'Rara',type:'Poção',attack:0,health:0,description:'+3 ATK.',image_url:img,effect_type:'buff_attack',effect_value:3,duration:2,trigger_type:'on_play',reactive_slot:null },
  { id:'et-12',name:'Escudo de Grayskull',cost:2,faction:'Eternia',rarity:'Rara',type:'Resposta',attack:0,health:0,description:'Bloqueia 4 dano.',image_url:img,effect_type:'prevent_damage',effect_value:4,duration:1,trigger_type:'on_react',reactive_slot:0 },
  { id:'et-13',name:'Benção da Sorceress',cost:3,faction:'Eternia',rarity:'Épica',type:'Poção',attack:0,health:0,description:'+2/+2 em aliado.',image_url:img,effect_type:'buff_stats',effect_value:2,duration:2,trigger_type:'on_play',reactive_slot:null },
  { id:'sm-1',name:'Skeletor',cost:11,faction:'Snake Mountain',rarity:'Lendária',type:'Criatura',attack:7,health:7,description:'Lorde maligno.',image_url:img,effect_type:'drain',effect_value:3,duration:null,trigger_type:'on_play',reactive_slot:null },
  { id:'sm-2',name:'Evil-Lyn',cost:7,faction:'Snake Mountain',rarity:'Épica',type:'Criatura',attack:4,health:5,description:'Controle arcano.',image_url:img,effect_type:'stun',effect_value:1,duration:1,trigger_type:'on_play',reactive_slot:null },
  { id:'sm-3',name:'Beast Man',cost:4,faction:'Snake Mountain',rarity:'Rara',type:'Criatura',attack:4,health:3,description:'Fúria bestial.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'sm-4',name:'Trap Jaw',cost:6,faction:'Snake Mountain',rarity:'Épica',type:'Criatura',attack:5,health:4,description:'Braço mecânico.',image_url:img,effect_type:'destroy_artifact',effect_value:1,duration:null,trigger_type:'on_play',reactive_slot:null },
  { id:'sm-5',name:'Mer-Man',cost:5,faction:'Snake Mountain',rarity:'Rara',type:'Criatura',attack:3,health:5,description:'Maré sombria.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'sm-6',name:'Tri-Klops',cost:3,faction:'Snake Mountain',rarity:'Comum',type:'Criatura',attack:3,health:2,description:'Precisão letal.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'sm-7',name:'Clawful',cost:2,faction:'Snake Mountain',rarity:'Comum',type:'Criatura',attack:2,health:2,description:'Pinça mortal.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'sm-8',name:'Webstor',cost:4,faction:'Snake Mountain',rarity:'Rara',type:'Criatura',attack:3,health:3,description:'Aprisiona inimigos.',image_url:img,effect_type:'root',effect_value:1,duration:1,trigger_type:'on_attack',reactive_slot:null },
  { id:'sm-9',name:'Whiplash',cost:3,faction:'Snake Mountain',rarity:'Comum',type:'Criatura',attack:2,health:4,description:'Cauda pesada.',image_url:img,effect_type:null,effect_value:null,duration:null,trigger_type:null,reactive_slot:null },
  { id:'sm-10',name:'Stinkor',cost:2,faction:'Snake Mountain',rarity:'Comum',type:'Criatura',attack:1,health:3,description:'Nuvem tóxica.',image_url:img,effect_type:'debuff_attack',effect_value:1,duration:1,trigger_type:'on_play',reactive_slot:null },
  { id:'sm-11',name:'Cajado de Havoc',cost:2,faction:'Snake Mountain',rarity:'Rara',type:'Poção',attack:0,health:0,description:'+3 dano mágico.',image_url:img,effect_type:'direct_damage',effect_value:3,duration:null,trigger_type:'on_play',reactive_slot:null },
  { id:'sm-12',name:'Veneno de Snake Mountain',cost:3,faction:'Snake Mountain',rarity:'Épica',type:'Poção',attack:0,health:0,description:'Dano por turno.',image_url:img,effect_type:'poison',effect_value:2,duration:2,trigger_type:'on_play',reactive_slot:null },
  { id:'sm-13',name:'Armadilha Sombria',cost:2,faction:'Snake Mountain',rarity:'Rara',type:'Resposta',attack:0,health:0,description:'Anula ataque.',image_url:img,effect_type:'counter_attack',effect_value:1,duration:1,trigger_type:'on_react',reactive_slot:0 },
  ...Array.from({ length: 24 }, (_, i) => ({
    id: `n-${i + 1}`,
    name: i < 10 ? `Mercenário ${i + 1}` : i < 16 ? `Fera Primeva ${i - 9}` : `Relíquia Universal ${i - 15}`,
    cost: (i % 7) + 1,
    faction: 'Neutral' as const,
    rarity: (i % 4 === 0 ? 'Rara' : i % 5 === 0 ? 'Épica' : 'Comum') as 'Comum' | 'Rara' | 'Épica',
    type: i > 17 ? ('Resposta' as const) : i > 13 ? ('Poção' as const) : ('Criatura' as const),
    attack: i > 13 ? 0 : (i % 5) + 1,
    health: i > 13 ? 0 : (i % 6) + 1,
    description: 'Carta neutra de suporte.',
    image_url: img,
    effect_type: i > 13 ? 'utility' : null,
    effect_value: i > 13 ? 1 : null,
    duration: i > 13 ? 1 : null,
    trigger_type: i > 13 ? 'on_play' : null,
    reactive_slot: i > 17 ? 0 : null,
  })),
];
